development:
  adapter: mysql2
  database: angularJS_development
  username: root
  password:
test:
  adapter: mysql2
  database: angularJS_test
  username: root
  password:
produvtoin:
  adapter: mysql2
  database: angularJS_test
  username: root
  password: